#!/bin/sh

OS=`uname`

#-------------------------------------------------------------------------------
# Installation.
#-------------------------------------------------------------------------------

Install(){
  [ "$1" = 'install' ] && {
    [ "$OS" = 'Darwin' ] && {
      cp .output/cog ../bin/macOS/
      sudo cp ../bin/macOS/cog /usr/local/bin
      echo "Installed!"
      return
    }
    [ "$OS" = 'Linux' ] && {
      cp .output/cog ../bin/macOS/
      sudo cp ../bin/macOS/cog /usr/local/bin
      echo "Installed!"
      return
    }
    cp .output/cog.exe ../bin/win64
  }
}


#-------------------------------------------------------------------------------
# Clean all files depending on the platform.
#-------------------------------------------------------------------------------

[ "$1" = 'clean' ] && {
  rm -rf tmp
  echo Cleaned!
  exit 0
}

#-------------------------------------------------------------------------------
# Apple macOS (Darwin)
#-------------------------------------------------------------------------------

[ "$OS" = 'Darwin' ] && {
  bin/macOS/cog --unity && {
    cd tmp && {
      ninja && {
        Install "$1"
      }
    }
  }
  exit 0
}

#-------------------------------------------------------------------------------
# Generate project for Linux (using Ninja or Make).
#-------------------------------------------------------------------------------

[ "$OS" = 'Linux' ] && {
# sudo update-alternatives --config c++
  bin/linux/cog --unity && {
    cd tmp && {
      ninja && {
        Install "$1"
      }
    }
  }
  exit 0
}

#-------------------------------------------------------------------------------
# Microsoft Windows and Visual Studio 2019.
#-------------------------------------------------------------------------------

bin/win64/cog.exe --unity
