#!/bin/sh
#-------------------------------------------------------------------------------
# Install cog into bin/*, ../eon/bin/*, and /usr/local/bin.
#-------------------------------------------------------------------------------
export ARCH=`uname -m`
export TARG=`uname`
echo "Updating for $TARG ($ARCH)"
case "$TARG" in
  Darwin)
    cp tmp/Build/Products/Release/cog ../eon/bin/macOS/
    cp tmp/Build/Products/Release/cog bin/macOS/
    sudo cp bin/macOS/cog /usr/local/bin
  ;;
esac
